#!/bin/bash

clear_eol="\r$(tput el)"

roster="roster"
rooms="rooms"

mkdir -p $roster
mkdir -p $rooms

login_user() {
    while true; do
        read -p "Enter your login: " login
        [ -z "$login" ] && exit 0

        if [ -e "$roster/$login" ]; then
            echo "This name is already taken." 1>&2
            continue
        fi

        if ! mkfifo "$roster/$login" &>/dev/null; then
            echo "Could not create user." 1>&2
            continue
        fi

        target="$login"
        break
    done
}

send_whisper() {
    echo "whisper> $login: $1" > "$roster/$2" &
}

send_channel_message() {
    for user in $rooms/$2/*; do
        echo "$2> $login: $1" > "$user" &
    done
}

join_channel() {
    mkdir -p "$rooms/$1"
    (cd "$rooms/$1" && ln -s "../../$roster/$login")
}

leave_channel() {
    rm "$rooms/$1/$login"
    rmdir "$rooms/$1" &>/dev/null
}

parse_message() {
    if [ "${1:0:1}" == "@" ]; then
        target="${1:1}"
        shift
        msg="$*"
    elif [ "$1" == "join" ]; then
        shift
        join_channel "$*"
        msg=""
    elif [ "$1" == "leave" ]; then
        shift
        leave_channel "$*"
        msg=""
    fi
}

handle_incoming() {
    [ ! -e "$roster/$login" ] && return

    exec 3<>"$roster/$login"
    while read -t0.1 -u3 line; do
        echo -e "${clear_eol}$(date +%R) $line"
    done
    exec 3>&-
}

main_loop() {
    while true; do
        handle_incoming

        echo -ne "\r$target> "          # refresh prompt
        read -t0.1 -N1 char             # timeout input
        [ -z "$char" ] && continue      # loop if no key

        unset msg
        echo -ne "$clear_eol"
        read -ep "$target> " -i"$char" msg      # now blocking input
        unset char

        [ "$msg" == "quit" ] && break

        parse_message $msg
        [ -z "$target" -o -z "$msg" ] && continue

        if [ -e "$roster/$target" ]; then
            send_whisper "$msg" "$target"
        elif [ -d "$rooms/$target" ]; then
            send_channel_message "$msg" "$target"
        else
            echo "Target does not exist." 1>&2
            target=""
        fi
    done
}

cleanup() {
    rm -r $rooms/*/$login &>/dev/null   # leave channels
    rmdir $rooms/* &>/dev/null          # remove empty channels
    rm "$roster/$login"                 # remove user pipe
    pkill -P "$$" &>/dev/null           # kill child processes
    exit 0
}

login_user
main_loop
cleanup
